# This keymap requires Massdrop Configurator support
OPT_DEFS += -DUSE_MASSDROP_CONFIGURATOR
OPT_DEFS += -DNO_PRINT
OPT_DEFS += -DNO_DEBUG

NKRO_ENABLE = yes
OPT_DEFS += -DFORCE_NKRO

COMBO_ENABLE = yes
OPT_DEFS += -DCOMBO_MUST_HOLD_MODS
